name: Terraform workflow

on:
  pull_request:
    paths:
      - 'terraform/**'
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose environment
        options:
          - dev
          - prd
      jobtype:
        type: choice
        description: Choose plan or apply for dev
        options:
          - plan
          - apply
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  
jobs:
  terraform:
    uses: bifrost-gha/.github/workflows/terraform.yml@main
    with:
      project_name: bifrost-core
      environment: ${{ inputs.environment }}
      jobtype: ${{ inputs.jobtype }}
      workflow-version: main