name: Terraform workflow
description: Runs terraform plan and apply based on labels and PR

on:
  # Only trigger if changes to terraform files
  pull_request:
    paths:
      - 'terraform/**'
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose environment
        options:
          - dev
          - prd
      jobtype:
        type: choice
        description: Choose plan or apply for dev
        options:
          - plan
          - apply
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  
jobs:
  uses: ./.github/workflows/terraform.yml
  with:
    project_name: bifrost-core
    environment: ${{ inputs.environment }}
    jobtype: ${{ inputs.jobtype }}
    workflow-version: main